
import type { Metadata } from "next";
import { DM_Sans, Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import BottomFooter from "@/components/BottomFooter";

const font =  Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={font.className}
      >
        {children}
        <Footer/>
        <BottomFooter/>
      </body>
    </html>
  );
}
